version: '3'

services:
  arm-selector:
    build:
      context: ./arm-selector
      dockerfile: Dockerfile
    environment:
      EXPERIMENTS_PARAMS_SERVICE_URL: http://experiment-params:8091/api/v1/experiment/
      REWARD_PREDICTOR_URL: http://reward-predictor:8092/api/v1/prediction

  experiment-params:
    build:
      context: ./experiments-params
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: jackpotian
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: experiment_db

  reward-predictor:
    build:
      context: ./reward-predictor
      dockerfile: Dockerfile
    environment:
      AWS_KEY: ${AWS_KEY}
      AWS_SECRET: ${AWS_SECRET}
      ENDPOINT: http://minio:9000
      S3_FORCE_PATH_STYLE: true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_USER: jackpotian
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: experiment_db

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: ${AWS_KEY}
      MINIO_SECRET_KEY: ${AWS_SECRET}
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    command: server /data

volumes:
  minio-data:
