{
 "title": "Experiment Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "experiment_id",
    "label": "experiment_id",
    "query": {
     "query": "label_values(model_accuracy,experiment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Model accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "model_accuracy{job=\"model-trainer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_accuracy{job=\"model-trainer\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Rewards Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rewards_service_rewards_created_events{experiment=\"$experiment_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewards Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rewards_service_rewards_updated_events{experiment=\"$experiment_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}