{
 "title": "Experiment Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "experiment_id",
    "label": "experiment_id",
    "query": {
     "query": "label_values(model_trainer_model_accuracy,experiment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Model accuracy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "model_trainer_model_accuracy{job=\"model-trainer\", experiment=\"$experiment_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model accuracy",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_trainer_model_accuracy{job=\"model-trainer\", experiment=\"$experiment_id\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Model updated ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(reward_predictor_model_updated{job=\"reward-predictor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model prediction count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(reward_predictor_model_predictions{job=\"reward-predictor\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewards Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rewards_service_rewards_created_events{experiment=\"$experiment_id\"}",
     "legendFormat": "{{experiment}}:{{arm}}"
    }
   ]
  },
  {
   "title": "Total Reward by arm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "rewards_service_rewards_updated_events{experiment=\"$experiment_id\"}",
     "legendFormat": "{{experiment}}:{{arm}}"
    }
   ]
  }
 ]
}