{
 "title": "Go Runtime Metrics",
 "description": "Process status and runtime metrics published by Go Prometheus client.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC duration quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{hostname}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "pointer deferences",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_lookups_total{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "Pointer dereferences"
      }
     ]
    }
   ]
  },
  {
   "title": "file descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "open fds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(process_open_fds{job=\"$job\", instance=~\"$host\"}[$interval])",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "goroutine stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_threads{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "alloc bytes allocated",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{job}} - bytes allocated"
      }
     ]
    },
    {
     "title": "alloc bytes allocated - derivative",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{job=\"$job\", instance=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - bytes allocated"
      }
     ]
    },
    {
     "title": "stack in use - bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{job}} - stack inuse"
      }
     ]
    },
    {
     "title": "stack in use - bytes - derivative",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\", instance=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - stack inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{hostname}} - heap inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes - derivative",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - heap inuse"
      }
     ]
    },
    {
     "title": "total alloc bytes allocation rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$host\"}[30s])",
       "legendFormat": "{{hostname}} - alloc rate"
      }
     ]
    }
   ]
  },
  {
   "title": "process memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "process resident memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{hostname}} - resident"
      }
     ]
    },
    {
     "title": "process resident memory derivative",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job=\"$job\", instance=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - resident"
      }
     ]
    },
    {
     "title": "process virtual memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\", instance=~\"$host\"}",
       "legendFormat": "{{hostname}} - virtual"
      }
     ]
    },
    {
     "title": "process virtual memory derivative",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(process_virtual_memory_bytes{job=\"$job\", instance=~\"$host\"}[$interval])",
       "legendFormat": "{{hostname}} - virtual"
      }
     ]
    }
   ]
  },
  {
   "title": "gin metrics (only for gin services)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "gin_requests_total{job=\"$job\", instance=~\"$host\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request count rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "rate(gin_requests_total{job=\"$job\", instance=~\"$host\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Response time avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "rate(gin_request_duration_seconds_sum{job=\"$job\", instance=~\"$host\"}[1m]) / rate(gin_request_duration_seconds_count{job=\"$job\", instance=~\"$host\"}[1m])",
     "legendFormat": "{{job}}-avg"
    }
   ]
  }
 ]
}